sudo: required
dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

php:
  - 7.0

env:
  matrix:
    - SCENARIO=none LIGHTNING=HEAD
    - SCENARIO=none LIGHTNING=STABLE
    - SCENARIO=dfs_dev LIGHTNING=STABLE
    - SCENARIO=dfs_tec LIGHTNING=STABLE

matrix:
  fast_finish: true
  allow_failures:
    - env: SCENARIO=none LIGHTNING=HEAD

addons:
  apt:
    packages:
    # Dependencies for Chrome.
    - libappindicator1
    - fonts-liberation

before_install:
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Update composer.
  - composer self-update
  - composer --version

  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  # Download Chrome Driver
  - LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - mkdir -p $HOME/.composer/vendor/bin
  - mv -f chromedriver $HOME/.composer/vendor/bin/
  - rm chromedriver_linux64.zip

  # Update Chrome.
  - export CHROME_BIN=/usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - rm google-chrome-stable_current_amd64.deb
  - google-chrome --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'df'@'localhost' IDENTIFIED BY 'df'; GRANT ALL ON drupal.* TO 'df'@'localhost';"

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Test Lightning HEAD
  - if [[ "$LIGHTNING" == HEAD ]]; then composer require "drupal/lightning:dev-2.x" --no-update; fi

  # We need Phing to execute our build steps.
  - composer global require phing/phing

  # Build the DF code base.
  - composer install

  # Download and install Drupal.org drush.
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Install DF cleanly so that settings.php will be created properly.
  - phing install -Ddb.database=drupal -Ddb.user=df -Ddb.password=df -Ddb.host=127.0.0.1 -Durl=http://127.0.0.1:8080

  # Import the fixture, if it exists.
  - phing recall -Dversion=$VERSION -Ddb.database=drupal -Ddb.user=df -Ddb.password=df -Ddb.host=127.0.0.1

  # If a scenario has been specified, enable it.
  - cd docroot
  - drush cache-rebuild
  - if [[ "$SCENARIO" != none ]]; then travis_wait drush es $SCENARIO; fi

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - jdk_switcher use oraclejdk8
  # Start Selenium and dump its ginormous log into a temporary file.
  - mkdir ../tmp
  - selenium-server-standalone -port 4444 -log ../tmp/selenium2.log &
  - sleep 5

script:
  - if [[ "$LIGHTNING" != HEAD ]]; then drush verify-makefile ../drupal-org.make; fi
  - if [[ "$LIGHTNING" != HEAD ]]; then composer validate ../composer.json --no-check-all --ansi --no-interaction; fi
  - if [[ "$SCENARIO" != none ]]; then behat --strict --stop-on-failure --config ./sites/default/files/behat.yml --tags=df; fi
  - if [[ "$SCENARIO" != none ]]; then behat --strict --stop-on-failure --config ./sites/default/files/behat.yml --tags=$SCENARIO; fi
