# This file is used by Acquia Pipelines continuous integration. It builds
# Demo Framework and runs its functional tests. Upon success, an artifact is
# deployed to the cddemo7 (63848917-680f-49c1-bddf-606b117fe71f) sub on Acquia
# cloud.
version: 1.0.0
services:
  - mysql

variables:
  global:
    SCENARIO: dfs_obio

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/bin:$PATH"
            - composer validate --no-check-all --ansi --no-interaction
            - composer install
      - install:
          type: script
          script:
            - cd $SOURCE_DIR
            - mysql -u root -proot -e 'CREATE DATABASE drupal;'
            - phing install -Ddb.password=root -Ddb.database=drupal -Durl=http://127.0.0.1:8080
            - cd docroot
            - echo $SCENARIO > scenario.txt;
            - if [[ "$SCENARIO" != none ]]; then ../bin/drush cache-rebuild; ../bin/drush es $SCENARIO; fi
            - cd ..
      - test:
          type: script
          script:
            - cd $SOURCE_DIR/docroot
            - drush runserver --default-server=builtin 8080 &>/dev/null &
            - phantomjs --webdriver=4444 > /dev/null &
            - sleep 10
            - behat --stop-on-failure --config ./sites/default/files/behat.yml --tags="df&&~javascript"
            - if [[ "$SCENARIO" != none ]]; then behat --stop-on-failure --config ./sites/default/files/behat.yml --tags="$SCENARIO&&~javascript"; fi
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          type: script
          script:
            - pipelines-deploy
      - cleanup:
          type: script
          script:
            # Setup settings file and codebase with minimum required for cloud.
            - cd $SOURCE_DIR
            - phing cloud-settings
  # When a GitHub pull request is merged, this deletes the corresponding ODE.
  pr-merged:
    steps:
      - deploy:
          type: script
          script:
            - pipelines-deploy

  # When a GitHub pull request is closed, this deletes the corresponding ODE.
  pr-closed:
    steps:
      - deploy:
          type: script
          script:
            - pipelines-deploy
