third_party_settings:
  better_formats:
    allowed_formats_toggle: 1
    allowed_formats:
      rich_text: rich_text
      full_html: 0
    default_order_toggle: 0
    default_order_wrapper:
      formats:
        rich_text:
          weight: '1'
        full_html:
          weight: '1'
