display:
  default:
    display_options:
      filters:
        type:
          value:
            article: article
            product: product
            location: location
          expose:
            reduce: true
        type_1:
          id: type_1
          table: node_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          operator: 'not in'
          value:
            landing_page: landing_page
            page: page
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          entity_type: node
          entity_field: type
          plugin_id: bundle
