zurb_foundation_page_site_name: 0
zurb_foundation_page_site_logo: 0
zurb_foundation_page_account_info: 0
zurb_foundation_top_bar_enable: 1
zurb_foundation_top_bar_sticky: 1
zurb_foundation_disable_base_css: 1
zurb_foundation_disable_base_js: 1
