<?php

/**
 * @file
 * Module for adding classes to blocks.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function block_class_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->hasPermission('administer block classes')) {

    /** @var \Drupal\block\BlockInterface $block */
    $block = $form_state->getFormObject()->getEntity();

    // This will automatically be saved in the third party settings.
    $form['third_party_settings']['#tree'] = TRUE;
    $form['third_party_settings']['block_class']['classes'] = array(
      '#type' => 'textfield',
      '#title' => t('CSS class(es)'),
      '#description' => t('Customize the styling of this block by adding CSS classes. Separate multiple classes by spaces.'),
      '#default_value' => $block->getThirdPartySetting('block_class', 'classes'),
    );

  }
}

/**
 * Implements hook_form_alter().
 */
function block_class_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'page_manager_display_variant_add_block_form':
    case 'page_manager_display_variant_edit_block_form':
      if (\Drupal::currentUser()->hasPermission('administer block classes')) {
        $display_variant_id = $form_state->get('display_variant_id');
        $block_id = $form_state->get('block_id');

        $page = $form_state->getBuildInfo()['args'][1];
        $display_variant = $page->getVariant($display_variant_id);
        $block = $display_variant->getBlock($block_id);
        $configuration = $block->getConfiguration();

        $form['settings']['classes'] = [
          '#type' => 'textfield',
          '#title' => t('CSS class(es)'),
          '#description' => t('Customize the styling of this block by adding CSS classes. Separate multiple classes by spaces.'),
          '#default_value' => isset($configuration['classes']) ? $configuration['classes'] : NULL,
        ];

        $form['#submit'][] = 'block_class_page_manager_display_variant_block_form_submit';
      }
      break;
  }
}

/**
 * Submit callback for page manager display variant forms to save class setting.
 */
function block_class_page_manager_display_variant_block_form_submit($form, FormStateInterface $form_state) {
  $display_variant_id = $form_state->get('display_variant_id');
  $block_id = $form_state->get('block_id');

  $page = $form_state->getBuildInfo()['args'][1];
  $display_variant = $page->getVariant($display_variant_id);
  $block = $display_variant->getBlock($block_id);
  $configuration = $block->getConfiguration();
  $settings = $form_state->getValue('settings');

  $display_variant->updateBlock($configuration['uuid'], ['classes' => $settings['classes']]);
  $page->save();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function block_class_preprocess_block(&$variables) {
  // Blocks coming from page manager widget does not have id.
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    if ($classes = $block->getThirdPartySetting('block_class', 'classes')) {
      $variables['attributes']['class'][] = $classes;
    }
  }

  // Page manager classes are stored in #configuration.
  if(!empty($variables['elements']['#configuration']['classes'])) {
    $variables['attributes']['class'][] = $variables['elements']['#configuration']['classes'];
  }
}
