# Schema for the views plugins of the Entity Gallery module.

views.area.entity_gallery_listing_empty:
  type: views_area
  label: 'Entity gallery link'

views.argument.entity_gallery_egid:
  type: views_argument
  label: 'Entity gallery ID'
  mapping:
    break_phrase:
      type: boolean
      label: 'Allow multiple values'
    not:
      type: boolean
      label: 'Exclude'

views.argument.entity_gallery_type:
  type: views_argument
  label: 'Entity gallery type'
  mapping:
    glossary:
      type: boolean
      label: 'Glossary mode'
    limit:
      type: integer
      label: 'Character limit'
    case:
      type: string
      label: 'Case'
    path_case:
      type: string
      label: 'Case in path'
    transform_dash:
      type: boolean
      label: 'Transform spaces to dashes in URL'
    break_phrase:
      type: boolean
      label: 'Allow multiple values'
    add_table:
      type: boolean
      label: 'Allow multiple filter values to work together'
    require_value:
      type: boolean
      label: 'Do not display items with no value in summary'

views.argument.entity_gallery_uid_revision:
  type: views_argument
  label: 'Entity gallery user ID'
  mapping:
    break_phrase:
      type: boolean
      label: 'Allow multiple values'
    not:
      type: boolean
      label: 'Exclude'

views.argument.entity_gallery_vid:
  type: views_argument
  label: 'Entity gallery revision ID'
  mapping:
    break_phrase:
      type: boolean
      label: 'Allow multiple values'
    not:
      type: boolean
      label: 'Exclude'

views.field.entity_gallery:
  type: views_field
  label: 'Entity gallery'
  mapping:
    link_to_entity_gallery:
      type: boolean
      label: 'Link this field to the original piece of content'

views.field.entity_gallery_bulk_form:
  type: views_field_bulk_form
  label: 'Entity gallery bulk form'

views.field.entity_gallery_path:
  type: views_field
  label: 'Entity gallery path'
  mapping:
    absolute:
      type: boolean
      label: 'Use absolute link (begins with "http://")'

views.field.entity_gallery_revision_link:
  type: views_field
  label: 'Link to an entity gallery revision'
  mapping:
    text:
      type: label
      label: 'Text to display'

views.field.entity_gallery_revision_link_delete:
  type: views_field
  label: 'Link to delete an entity gallery revision'
  mapping:
    text:
      type: label
      label: 'Text to display'

views.field.entity_gallery_revision_link_revert:
  type: views_field
  label: 'Link to revert an entity gallery to a revision'
  mapping:
    text:
      type: label
      label: 'Text to display'

views.filter.entity_gallery_access:
  type: views_filter
  label: 'Entity gallery access'

views.filter.entity_gallery_status:
  type: views_filter
  label: 'Entity gallery status'

views.filter.entity_gallery_uid_revision:
  type: views_filter
  label: 'Entity gallery revisions of an user'
  mapping:
    operator:
      type: string
      label: 'Operator'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: boolean
          label: 'Reduce'

views.filter_value.entity_gallery_access:
  type: string
  label: 'Access'

views.filter_value.entity_gallery_status:
  type: boolean
  label: 'Status'
