# Schema for the configuration files of the entity gallery module.

entity_gallery.type.*:
  type: config_entity
  label: 'Gallery type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    gallery_type:
      type: string
      label: 'Gallery type'
    gallery_type_bundles:
      type: sequence
      label: 'Gallery type bundles'
      sequence:
        type: string
        label: 'Bundle'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'
    display_submitted:
      type: boolean
      label: 'Display setting for author and date Submitted by post information'

# Plugin \Drupal\entity_gallery\Plugin\Search\EntityGallerySearch
search.plugin.entity_gallery_search:
  type: mapping
  label: 'Gallery search'
  mapping:
    rankings:
      type: sequence
      label: 'Gallery ranking'
      sequence:
        type: integer
        label: 'Influence'

action.configuration.entity_gallery_assign_owner_action:
  type: mapping
  label: 'Change the author of gallery configuration'
  mapping:
    owner_uid:
      type: text
      label: 'Username'

action.configuration.entity_gallery_publish_action:
  type: action_configuration_default
  label: 'Publish selected gallery configuration'

action.configuration.entity_gallery_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish selected gallery configuration'

action.configuration.entity_gallery_save_action:
  type: action_configuration_default
  label: 'Save gallery configuration'

action.configuration.entity_gallery_delete_action:
  type: action_configuration_default
  label: 'Delete gallery configuration'

action.configuration.entity_gallery_unpublish_by_keyword_action:
  type: mapping
  label: 'Unpublish gallery containing keyword(s) configuration'
  mapping:
    keywords:
      type: sequence
      label: 'Keywords'
      sequence:
        type: string
        label: 'Keyword'

condition.plugin.entity_gallery_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
