settings:
  toolbar:
    rows:
      -
        -
          name: 'Track Changes'
          items:
            - lite-acceptall
            - lite-acceptone
            - lite-rejectone
            - lite-toggleshow
            - lite-rejectall
