<?php

/**
 * @file dfs_fin_qa.module
 */

/**
 * Implements hook_entity_ENTITY_TYPE_view().
 */
function dfs_fin_qa_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\node\Entity\Node $entity */
  $entity = $build['#node'];
  if ($entity->bundle() == 'question') {
    $created = $entity->getCreatedTime();
    $build['created_date'] = ['#markup' => date('F jS, Y', $created)];

    // Hide the form if the current user doesn't have access.
    if (!\Drupal::currentUser()->hasPermission('answer questions')) {
      $build['field_answer'][0]['comment_form'] = [];
    }
  }
}

/**
 * Implements hook_entity_ENTITY_TYPE_view().
 */
function dfs_fin_qa_comment_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\comment\Entity\Comment $entity */
  $entity = $build['#comment'];
  if ($entity->bundle() == 'answer') {
    $created = $entity->getCreatedTime();
    $build['created_date'] = ['#markup' => date('F jS, Y', $created)];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dfs_fin_qa_form_comment_answer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['field_answer']['widget'][0]['value']['#title'] = '';
}
