dependencies:
  module:
    - crop
effects:
  3a3ecbd4-5b23-459c-b91e-5b080a7dca23:
    uuid: 3a3ecbd4-5b23-459c-b91e-5b080a7dca23
    id: crop_crop
    weight: -13
    data:
      crop_type: square

