dependencies:
  module:
    - crop
effects:
  95c3cb9c-7d93-4006-b3ad-176ad17bbc47:
    uuid: 95c3cb9c-7d93-4006-b3ad-176ad17bbc47
    id: crop_crop
    weight: -11
    data:
      crop_type: square

