field.widget.settings.inline_entity_form_preview:
  type: mapping
  label: 'Inline entity reference display format settings with preview'
  mapping:
    form_mode:
      type: string
      label: "Form mode"
    view_mode:
      type: string
      label: "View mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: string
      label: "Label (singular)"
    label_plural:
      type: string
      label: "Label (plural)"
    allow_new:
      type: boolean
      label: "Allow new"
    allow_existing:
      type: boolean
      label: "Allow existing"
    match_operator:
      type: string
      label: "Match operator"
