config_rewrite: replace
langcode: en
status: true
dependencies: {  }
name: thumbnail
label: 'Thumbnail (100×100)'
effects:
  c1815ac9-f69d-48f8-a301-fe87de0c3dd8:
    uuid: c1815ac9-f69d-48f8-a301-fe87de0c3dd8
    id: image_scale_and_crop
    weight: 2
    data:
      width: 100
      height: 100
