<?php

/**
 * @file
 * Contains dfs_obio_showroom.module.
 */

/**
 * Implements hook_scenario_import().
 */
function dfs_obio_showroom_scenario_import() {
  $migrations = [];
  $migrations['dfs_obio_showroom'] = [
    'import_file_demo_user_pictures',
    'import_user_demo_users',
    'import_dfs_obio_media_tags',
    'import_dfs_obio_image',
    'import_dfs_obio_tags',
    'import_dfs_obio_gallery_image',
    'import_dfs_obio_showroom_media_tags',
    'import_dfs_obio_showroom_image',
    'import_dfs_obio_showroom_tags',
    'import_dfs_obio_showroom_location',
    'import_dfs_obio_showroom_article',
    'import_dfs_obio_showroom_basic',
    'import_dfs_obio_showroom_hero',
    'import_dfs_obio_showroom_landing_page',
  ];
  return (array) $migrations;
}

/**
 * Implements hook_module_implements_alter().
 */
function dfs_obio_showroom_module_implements_alter(&$implementations, $hook) {
  // Ensure dynamic migrations get set in the right order.
  if ($hook == 'migration_plugins_alter') {
    $preferred_order = [
      'import',
      'df_tools_blocks',
      'df_tools_slideshow',
      'df_tools_migration',
      'df_tools_user',
      'dfs_obio',
      'dfs_obio_showroom',
    ];
    foreach ($preferred_order as $module) {
      if (isset($implementations[$module])) {
        unset($implementations[$module]);
        $implementations[$module] = $module;
      }
    }
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function dfs_obio_showroom_migration_plugins_alter(&$definitions) {
  // Update source references in scenario migrations.
  $import = dfs_obio_showroom_scenario_import();
  foreach ($import['dfs_obio_showroom'] as $id) {
    $source = &$definitions[$id]['source'];
    $prefix = 'import_dfs_obio_showroom';
    if (substr($id, 0, strlen($prefix)) === $prefix) {
      $source['path'] = str_replace('..', dirname(__FILE__), $source['path']);
      if (isset($source['constants']) && isset($source['constants']['source_base_path'])) {
        $source['constants']['source_base_path'] = str_replace('..', dirname(__FILE__), $source['constants']['source_base_path']);
      }
    }
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function dfs_obio_showroom_menu_links_discovered_alter(&$links) {
  unset($links['dfs_obio.about']);
  unset($links['dfs_obio.shop_office']);
  unset($links['dfs_obio.inspiration']); 
  unset($links['dfs_obio.locations']);
  unset($links['dfs_obio.cart']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dfs_obio_showroom_preprocess_html(&$variables) {
    $variables['attributes']['class'][] = 'dfs-obio-showroom';
}
